# Site settings
title: The new RubySpec blog
description: A blog about ruby/rubyspec.
baseurl: "/rubyspec"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: eregontp
github_username: eregon

# Build settings
markdown: kramdown
