name: CI
on: [push, pull_request]
jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
        ruby: [ 2.5.8, 2.6.6, 2.7.1 ]
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: true
    steps:
    - run: fail_unknown_command
